# Generated by Django 4.2.6 on 2023-10-24 00:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=200)),
                ('environment_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('social_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('governance_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('innovation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resource', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('human_rights', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_responsibility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workforce', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('community', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shareholders', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('csr_strategy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsgScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('polarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('environment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('social_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('governance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('innovation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resource', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('human_rights', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product_responsibility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workforce', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('community', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('management', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shareholders', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('csr_strategy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.companydetails')),
            ],
        ),
        migrations.AddField(
            model_name='companydetails',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sector'),
        ),
    ]
